title: Project Minimal
email: your-email@example.com
author: Melanie Hsieh
description: Speak from the heartËš
baseurl: "/projectminimal" 
url: "https://melaniehsieh.github.io" 

twitter_username: melaniehsieh
github_username: melaniehsieh

remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-feed

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site