title: Melanie Hsieh
email: your-email@example.com
description: 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://melaniehsieh.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: melaniehsieh
github_username: melaniehsieh

remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-feed

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-160880169-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site